import Head from "next/head"

export default function Layout(props) {
    const { children, title } = props
    return <div className="">
        <Head>
            <title>{title}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
            {children}
        </main>
        <footer className="">
            <span>Copyright Ranjithkumar © 2021</span>
        </footer>
    </div>
}